configuration: 
  name: treckba-retrieval
  author: ziy

persistence-provider:
  inherit: treckba-retrieval.persistence.local-persistence-provider

collection-reader:
  inherit: treckba-retrieval.collection.treckba-topic-collection-reader
  decorators: |
    - inherit: treckba-retrieval.collection.retrieval-gs-decorator-test

pipeline:
  - inherit: ecd.phase
    name: keyterm-extractor
    options: |
      - inherit: treckba-retrieval.keyterm.simple
#      - inherit: treckba-retrieval.keyterm.wikipedia-expanded

  - inherit: ecd.phase
    name: keyterm-update
    options: |
      - inherit: treckba-retrieval.keyterm.lucene-escape

  - inherit: ecd.phase
    name: retrieval-strategist
    options: |
      - inherit: treckba-retrieval.retrieval.simple-caching-query-test
#      - inherit: treckba-retrieval.retrieval.periodically-valid-caching-query-test

  - inherit: ecd.phase
    name: train-classifier
    options: |
      - inherit: treckba-retrieval.classify.libsvm-topic-independent-test
#      - inherit: treckba-retrieval.classify.libsvm-topic-specific-test
#      - inherit: treckba-retrieval.classify.random-forest-topic-specific-test
#      - inherit: treckba-retrieval.classify.random-forest-topic-independent-test
#      - inherit: treckba-retrieval.classify.logistic-topic-specific-test
#      - inherit: treckba-retrieval.classify.logistic-topic-independent-test
#      - inherit: treckba-retrieval.classify.nb-logreg-topic-specific-test
#      - inherit: treckba-retrieval.classify.nb-logreg-topic-independent-test
#      - inherit: base.noop

  - inherit: ecd.phase
    name: score-combiner
    options: |
      - inherit: treckba-retrieval.classify.score-combine

  - inherit: ecd.phase
    name: rescale
    options: |
      - inherit: treckba-retrieval.rescale.threshold-curve
      - inherit: treckba-retrieval.rescale.constant
#      - inherit: treckba-retrieval.rescale.minmax

  - inherit: ecd.phase
    name: filter
    options: |
      - inherit: treckba-retrieval.filter.threshold

  - inherit: treckba-retrieval.eval.retrieval-trace-evaluator-aggregator
    relevance-level: RELEVANCE # CENTRAL

post-process:
  - inherit: jdbc.eval.retrieval-evaluator-consumer

  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
