configuration: 
  name: treckba-retrieval
  author: ziy

persistence-provider:
  inherit: treckba-retrieval.persistence.local-persistence-provider

collection-reader:
  inherit: treckba-retrieval.collection.treckba-topic-collection-reader
  decorators: |
    - inherit: treckba-retrieval.collection.retrieval-gs-decorator-test

pipeline:
  - inherit: ecd.phase
    name: keyterm-expansion
    options: |
      - inherit: treckba-retrieval.keyterm.simple

  - inherit: ecd.phase
    name: retrieval-strategist
    options: |
      - inherit: treckba-retrieval.retrieval.caching-query-test
