configuration: 
  name: treckba-retrieval
  author: ziy

persistence-provider:
  inherit: treckba-retrieval.persistence.local-persistence-provider

collection-reader:
  inherit: treckba-retrieval.collection.treckba-topic-collection-reader
  decorators: |
    - inherit: treckba-retrieval.collection.retrieval-test-gs-decorator

pipeline:
  - inherit: ecd.phase
    name: keyterm-expansion
    options: |
      - inherit: treckba-retrieval.keyterm.simple

  - inherit: ecd.phase
    name: retrieval-strategist
    options: |
      - inherit: treckba-retrieval.retrieval.simple

  - inherit: treckba-retrieval.eval.retrieval-trace-evaluator-aggregator
    relevance-level: RELEVANCE

post-process:
  - inherit: jdbc.eval.retrieval-evaluator-consumer

  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
