configuration: 
  name: treckba-retrieval
  author: ziy

persistence-provider:
  inherit: treckba-retrieval.persistence.local-persistence-provider

collection-reader:
  inherit: treckba-retrieval.collection.treckba-topic-collection-reader
  decorators: |
    - inherit: treckba-retrieval.collection.retrieval-gs-decorator-test

pipeline:
  - inherit: ecd.phase
    name: keyterm-extractor
    options: |
      - inherit: treckba-retrieval.keyterm.wikipedia-expanded
#      - inherit: treckba-retrieval.keyterm.simple

  - inherit: ecd.phase
    name: keyterm-update
    options: |
      - inherit: treckba-retrieval.keyterm.lucene-escape

  - inherit: ecd.phase
    name: retrieval-strategist
    options: |
      - inherit: treckba-retrieval.retrieval.periodically-valid-queries-writer
#      - inherit: treckba-retrieval.retrieval.simple-queries-writer
